version: '3.3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb            # container name
    volumes:                           # volumes local storage
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      args:
        DB_DATABASE: ${DB_DATABASE}
        DB_USER_NAME: ${DB_USER_NAME}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file: .env
    restart: on-failure                # "on-failure", container will be restarted 

  nginx:           # with TLSv.1.2
    image: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:                       # wait for wp to start
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/html/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:                            #wait for mariadb to start
      - mariadb
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vsedat/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vsedat/data/mariadb'

networks:
    inception:
      driver: bridge